name: test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main
  workflow_dispatch:
    inputs:
      run_second_step:
        description: "Run second step"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

jobs:
  first-job:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.base_ref == 'main' && 'nonprod' || 'nonprod' }}
    steps:
      - name: First Step
        run: echo "first step"

  second-job:
    if: github.event.inputs.run_second_step == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Second Step
        run: echo "second step"
